name: hot_asset_gen
description: Hot-update Flutter assets via a local resource table + AssetBundle override.
version: 0.1.1
homepage: https://github.com/josercc/hot_asset_gen
repository: https://github.com/josercc/hot_asset_gen

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
